nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  annotations: {}
  name: ""

frontend:
  replicaCount: 1
  image:
    repository: harbor.apps.c6.numerique-interieur.com/mi-devops-d-day/tuto
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
    pullSecret: registry-pull-secret
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    type: ClusterIP
    port: 80
  container:
    port: 8080
  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
      - host: tuto-mono.dev.numerique-interieur.com
        paths:
          - path: /
            pathType: Prefix
    tls: []
    #  - secretName: tuto-mono.dev.numerique-interieur.com
    #    hosts:
    #      - tuto-mono.dev.numerique-interieur.com
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
